### ISSUE TITLE
I have this issue after updating the code.

### ISSUE THREAD

**Issue by threeneedone** [kadirnar/segment-anything-video#61]
I have this issue after updating the code.

Traceback (most recent call last):
  File "e:/AIGC/segment-anything-video/test", line 1, in <module>
    from metaseg import sahi_sliced_predict, SahiAutoSegmentation
  File "e:\AIGC\segment-anything-video\metaseg\__init__.py", line 7, in <module>
    from metaseg.falai_demo import falai_automask_image, falai_manuelmask_image
  File "e:\AIGC\segment-anything-video\metaseg\falai_demo.py", line 5, in <module>
    from metaseg import SegAutoMaskPredictor, SegManualMaskPredictor
ImportError: cannot import name 'SegAutoMaskPredictor' from partially initialized module 'metaseg' (most likely due to a circular import) (e:\AIGC\segment-anything-video\metaseg\__init__.py)

**Comment by Ericxgao** [comment]
Also having this issue.

**Comment by kadirnar** [comment]
Thank you for the feedback. I fixed it.

```
pip install metaseg==0.7.3
```
